<?php
session_start();
ob_start(); 
include '../dbConnection.php'; 
require_once __DIR__ . '/../vendor/autoload.php';

if (!isset($_SESSION['is_logged_in']) || !$_SESSION['is_logged_in']) {
    header("HTTP/1.1 403 Forbidden");
    exit;
}

$sql = "SELECT title, type, venue, 
               CONCAT(start_date, ' ', start_time, ' - ', end_date, ' ', end_time) AS timing
        FROM events
        ORDER BY start_date ASC";

$result = $conn->query($sql);

$pdf = new TCPDF();
$pdf->SetCreator('Event Hive');
$pdf->SetAuthor('Event Hive Management');
$pdf->SetTitle('Event Report');
$pdf->SetSubject('List of Events');
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(true, 10);
$pdf->AddPage();

$logo = '../assets/logo.png';
if (file_exists($logo)) {
    $pdf->Image($logo, 10, 10, 30); 
}

$pdf->Ln(10); 


$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 10, 'Event Report', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'A professional report of all scheduled events in Event Hive', 0, 1, 'C');
$pdf->Ln(5);


$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetFillColor(50, 130, 184); 
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(60, 10, 'Event Name', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Type', 1, 0, 'C', true);
$pdf->Cell(50, 10, 'Venue', 1, 0, 'C', true);
$pdf->Cell(50, 10, 'Timing', 1, 1, 'C', true);

$pdf->SetFont('helvetica', '', 11);
$pdf->SetTextColor(0, 0, 0); 

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(60, 10, $row['title'], 1, 0, 'C');
        $pdf->Cell(30, 10, ucfirst($row['type']), 1, 0, 'C');
        $pdf->Cell(50, 10, $row['venue'], 1, 0, 'C');
        $pdf->MultiCell(50, 10, $row['timing'], 1, 'C', 0, 1);
    }
} else {
    $pdf->Cell(190, 10, 'No events available', 1, 1, 'C');
}

$pdf->Ln(10);
$pdf->SetFont('helvetica', 'I', 10);
$pdf->Cell(0, 10, 'Generated by Event Hive | © ' . date('Y'), 0, 1, 'C');

ob_end_clean();
$pdf->Output('event_report.pdf', 'D'); 

$conn->close();
?>
